package:
  name: imaged11
  version: trunk

source:
  svn_url: http://svn.code.sf.net/p/fable/code/ImageD11/trunk

requirements:
  build:
    - numpy
  run:
    - fabio
    - lxml
    - numpy
    - pillow >=2.5.3
    - xfab

test:
  imports:
    - ImageD11

about:
  license: GPL
  home: https://sourceforge.net/projects/fable/
  summary: Fable software for analysis of 2D diffraction images by Jon Wright
